version: '3.7'

services:

  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/node_app/
      - docker-node:/opt/node_app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  docker-node: