version: '3.7'

services:

  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: npm run start:dev:docker
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  notused: